import next from 'eslint-config-next'
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import tseslint from 'typescript-eslint'

/**
 * SonoMusa Playground — lint configuration.
 *
 * The interesting part of this file is not the style rules. It is the LAYER
 * ENFORCEMENT below, which turns the architectural invariants in
 * docs/rules/01-architecture.md into errors instead of good intentions.
 *
 * Import direction is strictly downward:
 *
 *   src/content/**   manifests + media          (authored per project)
 *          ↓
 *   src/domain/**    schemas · repository       (pure TypeScript, zero React)
 *          ↓
 *   src/features/**  gallery · index · preview  (React, project-agnostic)
 *          ↓
 *   src/app/**       routes, metadata           (composition)
 */

/** Anything that would drag a rendering concern into the domain layer. */
const RENDERING_MODULES = [
  { name: 'react', message: 'The domain layer must stay free of React. See docs/rules/01-architecture.md.' },
  { name: 'react-dom', message: 'The domain layer must stay free of React. See docs/rules/01-architecture.md.' },
  { name: 'next', message: 'The domain layer must stay framework-agnostic. See docs/rules/01-architecture.md.' },
  { name: 'motion', message: 'Animation is a presentation concern and does not belong in the domain layer.' },
  { name: 'motion/react', message: 'Animation is a presentation concern and does not belong in the domain layer.' },
]

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'out/**',
      'build/**',
      'coverage/**',
      'next-env.d.ts',
      // Generated by scripts/generate-registry.ts — regenerate, never hand-edit.
      'src/content/projects/registry.generated.ts',
    ],
  },

  ...next,
  ...nextCoreWebVitals,

  // ─────────────────────────────────────────────────────────────────────────
  // Baseline
  // ─────────────────────────────────────────────────────────────────────────
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'prefer-const': 'error',
      'object-shorthand': 'error',
      'no-restricted-syntax': [
        'error',
        {
          selector: "TSEnumDeclaration",
          message: 'Prefer a union type or an `as const` object over `enum` — it survives erasure and stays serializable.',
        },
      ],
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // LAYER: domain — pure TypeScript. No React, no Next, no features, no app.
  // The one permitted content import is the local source adapter, below.
  // ─────────────────────────────────────────────────────────────────────────
  {
    files: ['src/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: RENDERING_MODULES,
          patterns: [
            {
              group: ['next/*', 'react/*'],
              message: 'The domain layer must stay framework-agnostic. See docs/rules/01-architecture.md.',
            },
            {
              group: ['@/features/*', '@/app/*', '@/components/*', '@/styles/*'],
              message:
                'Imports flow downward only. The domain layer cannot depend on presentation. See docs/rules/01-architecture.md.',
            },
            {
              group: ['@/content/*'],
              message:
                'Only src/domain/project/repository/sources/** may import content. Everything else goes through ProjectRepository.',
            },
          ],
        },
      ],
    },
  },

  // The single, deliberate exception: the local source adapter is the seam
  // where the content directory is bound to the repository port. Swapping this
  // file for a CMS adapter is the whole point of the boundary (CONCEPT §40).
  {
    files: ['src/domain/project/repository/sources/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: RENDERING_MODULES,
          patterns: [
            {
              group: ['@/features/*', '@/app/*', '@/components/*'],
              message: 'Imports flow downward only. See docs/rules/01-architecture.md.',
            },
          ],
        },
      ],
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // LAYER: features — shared, project-agnostic UI.
  // Must never reach into content, and must never know a project by name.
  // ─────────────────────────────────────────────────────────────────────────
  {
    files: ['src/features/**/*.{ts,tsx}', 'src/components/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/content/*', '@/content'],
              message:
                'Shared UI must not import project content. Receive validated Project objects as props instead. See docs/rules/01-architecture.md.',
            },
            {
              group: ['@/app/*'],
              message: 'Imports flow downward only — features cannot depend on routes.',
            },
          ],
        },
      ],
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // LAYER: content — manifests only. Authors touch the domain helper and
  // nothing else, so a manifest can never reach into the UI.
  // ─────────────────────────────────────────────────────────────────────────
  {
    files: ['src/content/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/features/*', '@/app/*', '@/components/*', '@/styles/*'],
              message:
                'A project manifest is data. It must not import UI. Interactive previews register a componentId instead. See docs/rules/02-content.md.',
            },
          ],
        },
      ],
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Scripts and tests — Node-facing, relaxed.
  // ─────────────────────────────────────────────────────────────────────────
  {
    files: ['scripts/**/*.ts', '**/*.test.ts', '**/*.test.tsx', 'vitest.config.ts'],
    rules: {
      'no-console': 'off',
    },
  },
)
